import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




interface Props {
  children: React.ReactNode;
}

export default function Layout({ children }: Props) {
  return (
    <ClerkProvider>
      <Header/>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="container mx-auto">
          <div className="flex items-start justify-center min-h-screen">
            <div className="mt-20">{children}</div>
        
        </div>
        </main>
      </body>
    </html>
     </ClerkProvider>
  );
}
